/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba2;

import javax.swing.JOptionPane;

/**
 *
 * @author ESFOT
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setSize(500, 450);

        btnCalcular.setEnabled(false);
        btnSeleccionarOtra.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeleccionar = new javax.swing.JButton();
        cmbLista = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtLado1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLado2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLado3 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        txtPerimetro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSeleccionarOtra = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnSeleccionar.setText("Seleccione");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionar);
        btnSeleccionar.setBounds(269, 36, 95, 23);

        cmbLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equilatero", "Escaleno", "Isósceles", "Rectangulo" }));
        cmbLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbLista);
        cmbLista.setBounds(127, 37, 102, 20);

        jLabel2.setText("LADO 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 99, 79, 14);

        txtLado1.setEnabled(false);
        txtLado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLado1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLado1);
        txtLado1.setBounds(110, 80, 90, 30);

        jLabel3.setText("LADO 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 172, 50, 14);

        txtLado2.setEnabled(false);
        txtLado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLado2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLado2);
        txtLado2.setBounds(110, 150, 86, 30);

        jLabel4.setText("LADO 3 ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 240, 70, 14);

        txtLado3.setEnabled(false);
        txtLado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLado3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLado3);
        txtLado3.setBounds(110, 230, 86, 30);

        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(269, 134, 125, 87);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ÁREA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 280, 86, 30);

        txtArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtArea.setEnabled(false);
        getContentPane().add(txtArea);
        txtArea.setBounds(150, 280, 178, 30);

        txtPerimetro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPerimetro.setEnabled(false);
        getContentPane().add(txtPerimetro);
        txtPerimetro.setBounds(150, 320, 178, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("PERÍMETRO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 320, 86, 30);

        btnSeleccionarOtra.setText("OTRO");
        btnSeleccionarOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarOtraActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarOtra);
        btnSeleccionarOtra.setBounds(340, 300, 110, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ALTURA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 360, 86, 30);

        txtAltura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAltura.setEnabled(false);
        getContentPane().add(txtAltura);
        txtAltura.setBounds(150, 360, 178, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLado1ActionPerformed

    private void txtLado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLado2ActionPerformed

    private void txtLado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLado3ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double perimetro;
        double area;
        double altura;
        String nombre = cmbLista.getSelectedItem().toString();

        //Equilatero, Escaleno, Isósceles, Rectangulo
        if (cmbLista.getSelectedIndex() == 0) {
            String lado = txtLado1.getText();
            if (!lado.equals("")) {
                double lado1 = Double.parseDouble(lado);
                double lado2 = Double.parseDouble(lado);
                double lado3 = Double.parseDouble(lado);

                Equilatero equi = new Equilatero(lado1, nombre);

                perimetro = equi.obtenerPerimetro();
                String periEqui = String.valueOf(perimetro);
                txtPerimetro.setText(periEqui);
                area = equi.obtenerArea();
                String areaEqui = String.valueOf(area);
                txtArea.setText(areaEqui);
                altura = equi.obtenerAltura();
                String alturaEqui = String.valueOf(altura);
                txtAltura.setText(alturaEqui);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar los campos");
            }

        } else if (cmbLista.getSelectedIndex() == 1) {
            String lad1 = txtLado1.getText();
            String lad2 = txtLado2.getText();
            String lad3 = txtLado3.getText();

            if (!lad1.equals("") && !lad2.equals("") && !lad3.equals("")) {
                if (!lad1.equals(lad2) && !lad1.equals(lad3) && !lad2.equals(lad3)) {

                    double lado1 = Double.parseDouble(lad1);
                    double lado2 = Double.parseDouble(lad2);
                    double lado3 = Double.parseDouble(lad3);

                    if ((lado1 + lado2 > lado3) && (lado2 + lado3 > lado1) && (lado1 + lado3 > lado2)) {
                        Escaleno esc = new Escaleno(lado1, lado2, lado3, nombre);
                        perimetro = esc.obtenerPerimetro();
                        String periTriangulo = String.valueOf(perimetro);
                        txtPerimetro.setText(periTriangulo);
                        area = esc.obtenerArea();
                        String areaTriangulo = String.valueOf(area);
                        txtArea.setText(areaTriangulo);
                        altura = esc.obtenerAltura();
                        String alturaEqui = String.valueOf(altura);
                        txtAltura.setText(alturaEqui);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Debe ingresar lados correctos ");

                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Debe ingresar todos los lados diferentes");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar todos los campos");
            }
        } else if (cmbLista.getSelectedIndex() == 2) {
            String lado1Rec = txtLado1.getText();
            String lado2Rec = txtLado2.getText();
            if (!lado1Rec.equals("") && !lado2Rec.equals("")) {
                double lado1 = Double.parseDouble(lado1Rec);
                double lado2 = Double.parseDouble(lado2Rec);
                double lado3 = (double) lado1;
                if ((lado1 + lado2 > lado3) && (lado2 + lado3 > lado1) && (lado1 + lado3 > lado2)&& lado1!=lado2) {
                    Isosceles is = new Isosceles(lado1, lado2, nombre);
                    perimetro = is.obtenerPerimetro();
                    String periRectangulo = String.valueOf(perimetro);
                    txtPerimetro.setText(periRectangulo);
                    area = is.obtenerArea();
                    String areaRectangulo = String.valueOf(area);
                    txtArea.setText(areaRectangulo);
                    altura = is.obtenerAltura();
                    String alturaIs = String.valueOf(altura);
                    txtAltura.setText(alturaIs);

                }else{
                    JOptionPane.showMessageDialog(rootPane, "Debe ingresar lados correctos ");

                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar todos los campos");
            }
        } else if (cmbLista.getSelectedIndex() == 3) {
            String lado1 = txtLado1.getText();
            String lado2 = txtLado2.getText();

            if (!lado1.equals("") && !lado2.equals("")) {
                double lad1 = Double.parseDouble(lado1);
                double lad2 = Double.parseDouble(lado2);
                double lad3 = (double) Math.sqrt(Math.pow(lad1, 2) + Math.pow(lad2, 2));
                Rectangulo c1 = new Rectangulo(lad1, lad2, lad3, nombre);
                System.out.println(""+lad3);
                perimetro = c1.obtenerPerimetro();
                String peri = String.valueOf(perimetro);
                txtPerimetro.setText(peri);
                area = c1.obtenerArea();
                String areaC = String.valueOf(area);
                txtArea.setText(areaC);
                altura = c1.obtenerAltura();
                String alturaR = String.valueOf(altura);
                txtAltura.setText(alturaR);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar todos los campos");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed

        btnSeleccionar.setEnabled(false);
        cmbLista.setEnabled(false);
        btnCalcular.setEnabled(true);
        btnSeleccionarOtra.setEnabled(true);
//Equilatero, Escaleno, Isósceles, Rectangulo
        if (cmbLista.getSelectedIndex() == 0) {
            //Cuadrado c1 = new Cuadrado (cmbListaFiguras.getSelectedItem().toString());

            txtLado1.setEnabled(true);

        } else if (cmbLista.getSelectedIndex() == 1) {

            txtLado1.setEnabled(true);
            txtLado2.setEnabled(true);
            txtLado3.setEnabled(true);

        } else if (cmbLista.getSelectedIndex() == 2) {
            txtLado1.setEnabled(true);
            txtLado2.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "INGRESE VALOR DE LADO REPETIDO EN (LADO1) Y EL VALOR DE LA BASE EN (LADO2)");

        } else if (cmbLista.getSelectedIndex() == 3) {
            txtLado1.setEnabled(true);
            txtLado2.setEnabled(true);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void cmbListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbListaActionPerformed

    private void btnSeleccionarOtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarOtraActionPerformed
        btnSeleccionar.setEnabled(true);
        btnCalcular.setEnabled(false);
        cmbLista.setEnabled(true);
        txtLado1.setEnabled(false);
        txtLado1.setText("");
        txtLado2.setEnabled(false);
        txtLado2.setText("");
        txtLado3.setEnabled(false);
        txtLado3.setText("");

        txtPerimetro.setEnabled(false);
        txtPerimetro.setText("");
        txtArea.setEnabled(false);
        txtArea.setText("");
        txtAltura.setEnabled(false);
        txtAltura.setText("");
        btnSeleccionarOtra.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarOtraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnSeleccionarOtra;
    private javax.swing.JComboBox<String> cmbLista;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtLado1;
    private javax.swing.JTextField txtLado2;
    private javax.swing.JTextField txtLado3;
    private javax.swing.JTextField txtPerimetro;
    // End of variables declaration//GEN-END:variables
}
